/* Generated by automated build script */
#define PRERELEASE 0.77
#define TEXTVER "Pre-release 0.77:2022-02-09.9427f96"
#define SSHVER "-Prerelease-0.77:20220209.9427f96"
#define BINARY_VERSION 0,76,33982,0
